### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by marcosfvc** [code4func/flutter-taxiapp#5]

**Comment by jerygit1990** [comment]
First of all, Thanks for your interesting about this tutorial,
Now I have no longer keep going with it for a busy.
I can guess you missing a "google_map_flutter" module. So have you
downloaded it? In the video I have step by step to config it

Vào Th 4, 28 thg 8, 2019 vào lúc 23:51 Marcos Villar <
notifications@github.com> đã viết:
